### ISSUE TITLE
A320 (Fly-by-wire A32X mod) has only 1-way communication with COM1

### ISSUE THREAD

**Issue by VVingnut** [mracko/MSFS-Mobile-Companion-App#17] opened 2021-01-02 10:34 UTC
Able to READ COM1 Standby and Active frequencies but unable to SET them.  Tried both Direct Mode and Active Swap.

Other features (Lights, NAV, MAP) appear to be working correctly.

**Comment by mracko** [comment] 2021-01-02 20:39
My experience is that the COM frequencies on the A320 (at least the default) actually work "under the hood". That means that I can see the change when I open up the ATC window but not in the cockpit. The only way to force an update of the frequencies in the cockpit is to switch from VHF1 to VHF2 and then back to VHF1. This is if you're changing COM1.

Please let me know if you're also seeing this.

**Comment by VVingnut** [comment] 2021-01-03 03:45
Roger that.  Can confirm that even though the COM settings on the RADIO are unchanged - The ATC FREQ does change and also is reflected in my ability to communicate with VATSIM ATC at the FREQ set in your utility.

I'm very happy about this because setting the COM FREQUENCY in FS2020 is frustrating and slow.  

Kind regards,

VVingnut

**Comment by mracko** [comment] 2021-01-03 09:34
Great to hear that. I'll close this issue since this seems to be caused by the plane (both default and FBW mod) and not by the app. Unfortunately, there isn't much I can do about it now. All the other planes seem to work fine except the A320.

I'll post an issue over at the FBW GitHub page. Maybe they can find a solution.

Thanks a lot!

**Closed by mracko** 2021-01-03 09:34 UTC
